name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
main: ${mainClass}
depend: [Base]
commands: 
  pvpgunplus:
    description:
    usage:
permissions:
  pvpgunplus:
    description: Used for guns
    default: op