name: ${name}
version: ${version} b${jenkins.buildNumber} ${git.branch}/${git.commit.id.abbrev}
description: ${description}
author: ${author}
website: ${url}
main: ${mainClass}
depend: [Base]
commands: 
  pvpgunplus:
    description:
    usage:
permissions:
  pvpgunplus:
    description: Used for guns
    default: op