name: ${name}
version: ${version} b${git.build.number} ${git.branch}/${git.commit.id.abbrev}
description: ${description}
author: ${author}
website: ${url}
main: ${mainClass}
depend: [ Base ]
commands: