name: OldGuns
version: 1.0-SNAPSHOT
description: Deprecated old Guns plugin that we still use for some reason
author: Orange
website: http://www.brawl.com
main: com.orange451.pvpgunplus.PVPGunPlus
depend: [Base]
commands: 
  pvpgunplus:
    description:
    usage:
permissions:
  pvpgunplus:
    description: Used for guns
    default: op